"""Pydantic request and response schemas."""
from __future__ import annotations

from app.schemas.auth import (
    ForgotPasswordRequest,
    LoginRequest,
    LoginResponse,
    MembershipRead,
    MessageResponse,
    OrganizationRead as AuthOrganizationRead,
    RegisterRequest,
    RegisterResponse,
    ResetPasswordRequest,
    TokenRefreshResponse,
    UserProfileResponse as AuthUserProfileResponse,
    UserRead,
    VerifyEmailRequest,
)
from app.schemas.client import (
    ClientCreateRequest,
    ClientListItem,
    ClientMemoryResponse,
    ClientResponse,
    MeetingRead,
    PreMeetingBriefResponse,
)
from app.schemas.workspace import (
    MemberRead,
    WorkspaceInviteAcceptResponse,
    WorkspaceInviteRequest,
    WorkspaceInviteResponse,
    WorkspaceItem,
    WorkspaceListResponse,
    WorkspaceMemberDeleteResponse,
    WorkspaceMemberRoleUpdateRequest,
    WorkspaceMemberRoleUpdateResponse,
    WorkspaceRead,
    WorkspaceSwitchRequest,
    WorkspaceSwitchResponse,
)

__all__ = [
    "AuthOrganizationRead",
    "AuthUserProfileResponse",
    "ClientCreateRequest",
    "ClientListItem",
    "ClientMemoryResponse",
    "ClientResponse",
    "ForgotPasswordRequest",
    "LoginRequest",
    "LoginResponse",
    "MeetingRead",
    "MemberRead",
    "MembershipRead",
    "MessageResponse",
    "PreMeetingBriefResponse",
    "RegisterRequest",
    "RegisterResponse",
    "ResetPasswordRequest",
    "TokenRefreshResponse",
    "UserProfileResponse",
    "UserRead",
    "VerifyEmailRequest",
    "WorkspaceInviteAcceptResponse",
    "WorkspaceInviteRequest",
    "WorkspaceInviteResponse",
    "WorkspaceItem",
    "WorkspaceListResponse",
    "WorkspaceMemberDeleteResponse",
    "WorkspaceMemberRoleUpdateRequest",
    "WorkspaceMemberRoleUpdateResponse",
    "WorkspaceRead",
    "WorkspaceSwitchRequest",
    "WorkspaceSwitchResponse",
]
