"""Add audio_path and new meeting states

Revision ID: 0fe3ff663673
Revises: g4b2c3d4e5f7
Create Date: 2026-07-31 12:08:25.532609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe3ff663673'
down_revision: Union[str, None] = 'g4b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_organization_id', table_name='clients')
    op.drop_index('ix_clients_user_id', table_name='clients')
    op.drop_column('clients', 'user_id')
    op.drop_column('clients', 'organization_id')
    op.drop_column('commitment_meeting_links', 'updated_at')
    op.drop_index('ix_commitments_organization_id', table_name='commitments')
    op.drop_index('ix_commitments_user_id', table_name='commitments')
    op.drop_column('commitments', 'user_id')
    op.drop_column('commitments', 'organization_id')
    op.drop_constraint('meeting_evidence_organization_id_fkey', 'meeting_evidence', type_='foreignkey')
    op.drop_constraint('meeting_evidence_user_id_fkey', 'meeting_evidence', type_='foreignkey')
    op.add_column('meetings', sa.Column('audio_path', sa.String(length=255), nullable=True))
    op.drop_index('ix_meetings_organization_id', table_name='meetings')
    op.drop_index('ix_meetings_user_id', table_name='meetings')
    op.drop_column('meetings', 'user_id')
    op.drop_column('meetings', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('organization_id', sa.VARCHAR(), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('user_id', sa.VARCHAR(), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False))
    op.create_index('ix_meetings_user_id', 'meetings', ['user_id'], unique=False)
    op.create_index('ix_meetings_organization_id', 'meetings', ['organization_id'], unique=False)
    op.drop_column('meetings', 'audio_path')
    op.create_foreign_key('meeting_evidence_user_id_fkey', 'meeting_evidence', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('meeting_evidence_organization_id_fkey', 'meeting_evidence', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('commitments', sa.Column('organization_id', sa.VARCHAR(), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False))
    op.add_column('commitments', sa.Column('user_id', sa.VARCHAR(), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False))
    op.create_index('ix_commitments_user_id', 'commitments', ['user_id'], unique=False)
    op.create_index('ix_commitments_organization_id', 'commitments', ['organization_id'], unique=False)
    op.add_column('commitment_meeting_links', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('organization_id', sa.VARCHAR(), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('user_id', sa.VARCHAR(), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False))
    op.create_index('ix_clients_user_id', 'clients', ['user_id'], unique=False)
    op.create_index('ix_clients_organization_id', 'clients', ['organization_id'], unique=False)
    # ### end Alembic commands ###
