"""Add core models and tenant mixin

Revision ID: 16ebe227ba0d
Revises: ccfc6cb6ee01
Create Date: 2026-07-26 14:36:23.080715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ebe227ba0d'
down_revision: Union[str, None] = 'ccfc6cb6ee01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.add_column('clients', sa.Column('organization_id', sa.String(), nullable=False, server_default='SYSTEM'))
    op.add_column('clients', sa.Column('user_id', sa.String(), nullable=False, server_default='SYSTEM'))
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.add_column('commitment_meeting_links', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.add_column('commitments', sa.Column('organization_id', sa.String(), nullable=False, server_default='SYSTEM'))
    op.add_column('commitments', sa.Column('user_id', sa.String(), nullable=False, server_default='SYSTEM'))
    op.create_index(op.f('ix_commitments_organization_id'), 'commitments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commitments_user_id'), 'commitments', ['user_id'], unique=False)
    op.add_column('meetings', sa.Column('organization_id', sa.String(), nullable=False, server_default='SYSTEM'))
    op.add_column('meetings', sa.Column('user_id', sa.String(), nullable=False, server_default='SYSTEM'))
    op.create_index(op.f('ix_meetings_organization_id'), 'meetings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organization_id'), table_name='meetings')
    op.drop_column('meetings', 'user_id')
    op.drop_column('meetings', 'organization_id')
    op.drop_index(op.f('ix_commitments_user_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_organization_id'), table_name='commitments')
    op.drop_column('commitments', 'user_id')
    op.drop_column('commitments', 'organization_id')
    op.drop_column('commitment_meeting_links', 'updated_at')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_column('clients', 'user_id')
    op.drop_column('clients', 'organization_id')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
