"""Add timezone to NotificationPreference

Revision ID: 22ee53e99b7a
Revises: dd8340ff803d
Create Date: 2026-07-29 01:31:27.254606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ee53e99b7a'
down_revision: Union[str, None] = 'dd8340ff803d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'timezone')
    # ### end Alembic commands ###
