"""Day 3 telemetry

Revision ID: 23ca372069ef
Revises: 16ebe227ba0d
Create Date: 2026-07-27 06:49:58.873695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ca372069ef'
down_revision: Union[str, None] = '16ebe227ba0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_extraction_logs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('ai_extraction_logs', sa.Column('cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_extraction_logs', 'cost_usd')
    op.drop_column('ai_extraction_logs', 'latency_ms')
    # ### end Alembic commands ###
