"""add_communication_log

Revision ID: 2fa302439a88
Revises: 2d7e8f9a0b1c
Create Date: 2026-09-03 12:08:55.435628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa302439a88'
down_revision: Union[str, None] = '2d7e8f9a0b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    status_enum = ENUM('PENDING', 'SENT', 'FAILED', 'DELIVERED', 'READ', name='deliverystatus', create_type=False)
    
    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'EMAIL', 'SMS', name='communicationchannel'), nullable=False),
    sa.Column('message_content', sa.String(), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_client_id'), 'communication_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.create_index(op.f('ix_communication_logs_organization_id'), 'communication_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_user_id'), 'communication_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_logs_user_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_organization_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_client_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    # ### end Alembic commands ###
