"""update_vector_size_bge_m3

Revision ID: 89fc4269e052
Revises: c3a4e77c665d
Create Date: 2026-08-24 23:39:54.599486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '89fc4269e052'
down_revision: Union[str, None] = 'c3a4e77c665d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_evidence', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('meeting_evidence', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=False)
    # ### end Alembic commands ###
