"""add provider_message_id to communication_logs

Revision ID: 924be62947b0
Revises: 2fa302439a88
Create Date: 2026-09-03 13:11:29.935848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924be62947b0'
down_revision: Union[str, None] = '2fa302439a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_logs', sa.Column('provider_message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_communication_logs_provider_message_id'), 'communication_logs', ['provider_message_id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_logs_provider_message_id'), table_name='communication_logs')
    op.drop_column('communication_logs', 'provider_message_id')
    # ### end Alembic commands ###
