"""add audio_duration_seconds

Revision ID: b0da14c0bddb
Revises: 0fe3ff663673
Create Date: 2026-08-03 22:55:49.039304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0da14c0bddb'
down_revision: Union[str, None] = '0fe3ff663673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('audio_duration_seconds', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'audio_duration_seconds')
    # ### end Alembic commands ###
