"""Add Day 1 and Day 4 models

Revision ID: bb88f5a4f089
Revises: 23ca372069ef
Create Date: 2026-07-27 20:53:36.043648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb88f5a4f089'
down_revision: Union[str, None] = '23ca372069ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('commitment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('is_due_today', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_tasks_client_id'), 'follow_up_tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_due_date'), 'follow_up_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_id'), 'follow_up_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_organization_id'), 'follow_up_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_user_id'), 'follow_up_tasks', ['user_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_client_id'), 'risk_signals', ['client_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_id'), 'risk_signals', ['id'], unique=False)
    op.create_index(op.f('ix_risk_signals_organization_id'), 'risk_signals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_user_id'), 'risk_signals', ['user_id'], unique=False)
    op.add_column('meetings', sa.Column('source_type', sa.String(length=40), nullable=False, server_default='pasted_note'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'source_type')
    op.drop_index(op.f('ix_risk_signals_user_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_organization_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_client_id'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_follow_up_tasks_user_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_organization_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_due_date'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_client_id'), table_name='follow_up_tasks')
    op.drop_table('follow_up_tasks')
    # ### end Alembic commands ###
