"""Add cascade deletes to child tables

Revision ID: c3a4e77c665d
Revises: h5c3d4e5f6g7
Create Date: 2026-08-24 00:54:29.296531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a4e77c665d'
down_revision: Union[str, None] = 'h5c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_extraction_logs_meeting_id_fkey'), 'ai_extraction_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_extraction_logs', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('commitment_meeting_links_meeting_id_fkey'), 'commitment_meeting_links', type_='foreignkey')
    op.drop_constraint(op.f('commitment_meeting_links_commitment_id_fkey'), 'commitment_meeting_links', type_='foreignkey')
    op.create_foreign_key(None, 'commitment_meeting_links', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commitment_meeting_links', 'commitments', ['commitment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('commitments_client_id_fkey'), 'commitments', type_='foreignkey')
    op.create_foreign_key(None, 'commitments', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('follow_up_tasks_commitment_id_fkey'), 'follow_up_tasks', type_='foreignkey')
    op.drop_constraint(op.f('follow_up_tasks_client_id_fkey'), 'follow_up_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'follow_up_tasks', 'commitments', ['commitment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follow_up_tasks', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('meetings_client_id_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('risk_signals_client_id_fkey'), 'risk_signals', type_='foreignkey')
    op.drop_constraint(op.f('risk_signals_meeting_id_fkey'), 'risk_signals', type_='foreignkey')
    op.create_foreign_key(None, 'risk_signals', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'risk_signals', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_signals', type_='foreignkey')
    op.drop_constraint(None, 'risk_signals', type_='foreignkey')
    op.create_foreign_key(op.f('risk_signals_meeting_id_fkey'), 'risk_signals', 'meetings', ['meeting_id'], ['id'])
    op.create_foreign_key(op.f('risk_signals_client_id_fkey'), 'risk_signals', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_client_id_fkey'), 'meetings', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'follow_up_tasks', type_='foreignkey')
    op.drop_constraint(None, 'follow_up_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('follow_up_tasks_client_id_fkey'), 'follow_up_tasks', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('follow_up_tasks_commitment_id_fkey'), 'follow_up_tasks', 'commitments', ['commitment_id'], ['id'])
    op.drop_constraint(None, 'commitments', type_='foreignkey')
    op.create_foreign_key(op.f('commitments_client_id_fkey'), 'commitments', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'commitment_meeting_links', type_='foreignkey')
    op.drop_constraint(None, 'commitment_meeting_links', type_='foreignkey')
    op.create_foreign_key(op.f('commitment_meeting_links_commitment_id_fkey'), 'commitment_meeting_links', 'commitments', ['commitment_id'], ['id'])
    op.create_foreign_key(op.f('commitment_meeting_links_meeting_id_fkey'), 'commitment_meeting_links', 'meetings', ['meeting_id'], ['id'])
    op.drop_constraint(None, 'ai_extraction_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ai_extraction_logs_meeting_id_fkey'), 'ai_extraction_logs', 'meetings', ['meeting_id'], ['id'])
    # ### end Alembic commands ###
