"""initial postgres schema

Revision ID: ccfc6cb6ee01
Revises: 
Create Date: 2026-07-26 12:25:59.034746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfc6cb6ee01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=140), nullable=False),
    sa.Column('products_owned_json', sa.Text(), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=False),
    sa.Column('relationship_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_normalized_name'), 'clients', ['normalized_name'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('normalized_description', sa.String(length=520), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_date_text', sa.String(length=120), nullable=True),
    sa.Column('due_date_confidence', sa.Float(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_client_id'), 'commitments', ['client_id'], unique=False)
    op.create_index(op.f('ix_commitments_due_date'), 'commitments', ['due_date'], unique=False)
    op.create_index(op.f('ix_commitments_id'), 'commitments', ['id'], unique=False)
    op.create_index(op.f('ix_commitments_normalized_description'), 'commitments', ['normalized_description'], unique=False)
    op.create_index(op.f('ix_commitments_status'), 'commitments', ['status'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_discussion_points_json', sa.Text(), nullable=False),
    sa.Column('concerns_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('client_identification_status', sa.String(length=60), nullable=False),
    sa.Column('client_identification_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('ai_extraction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('raw_response_json', sa.Text(), nullable=False),
    sa.Column('parsed_response_json', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitment_meeting_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commitment_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitment_meeting_links_commitment_id'), 'commitment_meeting_links', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_commitment_meeting_links_meeting_id'), 'commitment_meeting_links', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitment_meeting_links_meeting_id'), table_name='commitment_meeting_links')
    op.drop_index(op.f('ix_commitment_meeting_links_commitment_id'), table_name='commitment_meeting_links')
    op.drop_table('commitment_meeting_links')
    op.drop_table('ai_extraction_logs')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_commitments_status'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_normalized_description'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_due_date'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_client_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_clients_normalized_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
